services:
  keycloak:
    image: quay.io/maurycy_krzeminski/keycloak
    container_name: keycloak
    ports:
      - "1234:8080"
    environment: # see https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_METRICS_ENABLED: "false"
  smtp:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
      - "1025:1025"

